### ISSUE TITLE
Shutting down, restarts

### ISSUE THREAD

**Issue by mrgooge** [korzhyk/OpenCore-Maximus-X-Code#1]
I have the same hardware as you, and I have Opencore (0.5.6) working, but, I can't shutdown... When I choose Shutdown, the computer restarts. Does this happen on your system? Thanks!

**Comment by korzhyk** [comment]
@mrgooge hello, your issue is not related to my config.

**Comment by mrgooge** [comment]
Yes, thank you for your reply. I did fix it by applying a BIOS change.

**Comment by trucnv** [comment]
Hi @mrgooge. Please let me know how you fixed it. I have the same problem. When I choose Shutdown, the computer restart. Thanks

**Comment by mrgooge** [comment]
For me I could fix it with either a BIOS change, on my ASUS ROG Maximus X Hero Z370. 
going into BIOS - Advanced\APM Configuration, and set ErP Ready Enable (S5).

...or...you can do this (but don't do both!) in Opencore

https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html

**Comment by trucnv** [comment]
@mrgooge Thanks for your suggestion. I will try it

**Comment by trucnv** [comment]
I can't find APM Configuration on BIOS with my HP Elitebook Folio G3 laptop. I also followed the guide: https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html
The part I’m getting stuck on is this:

To find the USB Controller that needs fixing, search for _PRW in your DSDT and see what Device is mentioned within it, generally this will be something like SB.PCI0.XHC.

In my DSDT there are a lot of entries that have _PRW and I can’t see anything about devices as mentioned. Can you help me?
