### ISSUE TITLE
Big Sur 11.xx

### ISSUE THREAD

**Issue by CrazyCreator13** [korzhyk/OpenCore-Maximus-X-Code#2]
an update for big sur is to be expected

**Comment by korzhyk** [comment]
@CrazyCreator13 I think current configuration can handle Big Sur.

**Comment by korzhyk** [comment]
@CrazyCreator13 and yes, it's runs like a charm. 
![Screen Shot 2021-02-07 at 10 54 54](https://user-images.githubusercontent.com/1100134/107141662-ff73ea00-6932-11eb-9e85-402a7f376445.png)

**Comment by CrazyCreator13** [comment]
Perfect ... Thanks for the answer
