### ISSUE TITLE
Z370m Pro 4 with Gigabyte RX570 

### ISSUE THREAD

**Issue by c-support** [korzhyk/OpenCore-Maximus-X-Code#3]
Hi friend, Im having many problems with my system I can't get a good EFI file, I have tried with many others and all time freeze no mater what I'm doing and is randomly, for now Im going to use this OpenCore-Maximus-X-Code but I really appreciate if you could bring me your help to resolve this I'm losing my mind. 

thanks.

Carlos

**Comment by korzhyk** [comment]
@c-support this config is for ASUS ROG Maximus X code with integrated Intel 8700K UHD 630 graphics. So your issue not related to OC configuration in this repository.
